version: "3.9"
services:
  web:
    build: .
    image: webapp:tag
    ports:
      - "8888:8888"
    volumes:
      - .:/codeS
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      GRANT_SUDO: "yes"