version: "3.9"
services:
  webb:
    build: .
    image: jupyter-qiskit
    ports:
      - "8888:8888"
    volumes:
      - .:/code
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      GRANT_SUDO: "yes"





